// frontend/src/routes/(app)/tag/+page.svelte
<script lang="ts">
	import { Badge } from '$lib/components/ui/badge';
	import * as Pagination from '$lib/components/ui/pagination';
	import { Tags } from '@lucide/svelte';
	import { goto } from '$app/navigation';
	import { resolve } from '$app/paths';

	let { data } = $props();
</script>

<svelte:head>
	<title>Tags | Shoka</title>
</svelte:head>

<div class="mx-auto max-w-screen-2xl px-4 py-8 sm:px-6">
	<div class="mb-6 flex items-center gap-2">
		<Tags class="size-5 text-muted-foreground" />
		<h1 class="text-2xl font-bold">Tags</h1>
		<span class="text-sm text-muted-foreground">({data.total})</span>
	</div>

	{#if data.tags.length === 0}
		<p class="text-muted-foreground">No tags found.</p>
	{:else}
		<div class="grid grid-cols-2 gap-2 sm:grid-cols-3 md:grid-cols-4 lg:grid-cols-5 xl:grid-cols-6">
			{#each data.tags as tag (tag.id)}
				<Badge
					href={resolve(`/tag/${encodeURIComponent(tag.name)}`)}
					variant="outline"
					class="h-auto w-full justify-between rounded-md text-sm"
				>
					<span class="truncate">{tag.name}</span>
					<span class="text-muted-foreground">{tag.count}</span>
				</Badge>
			{/each}
		</div>
	{/if}

	{#if data.total > data.limit}
		<div class="mt-8">
			<Pagination.Root
				count={data.total}
				perPage={data.limit}
				page={data.page}
				onPageChange={(p) => goto(resolve(`/tag?page=${p}`), { noScroll: true })}
			>
				{#snippet children({ pages })}
					<Pagination.Content>
						<Pagination.Item>
							<Pagination.Previous />
						</Pagination.Item>
						{#each pages as p (p.key)}
							{#if p.type === 'ellipsis'}
								<Pagination.Item>
									<Pagination.Ellipsis />
								</Pagination.Item>
							{:else}
								<Pagination.Item>
									<Pagination.Link page={p} isActive={data.page === p.value} />
								</Pagination.Item>
							{/if}
						{/each}
						<Pagination.Item>
							<Pagination.Next />
						</Pagination.Item>
					</Pagination.Content>
				{/snippet}
			</Pagination.Root>
		</div>
	{/if}
</div>

// frontend/app/pages/tag/index.vue
<script setup lang="ts">
import Button from "~/components/ui/button/Button.vue";
import Separator from "~/components/ui/separator/Separator.vue";

useHead({
  title: "Tags",
});

const { data: tags } = await useFetch("/api/tag", {
  key: "tags",
});
</script>

<template>
  <div>
    <h1 class="flex justify-center py-4 font-semibold text-2xl tracking-tight">
      Tags
    </h1>
    <div
      class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 2xl:grid-cols-6 gap-1.5 px-8 py-4"
    >
      <NuxtLink
        v-for="(tag, index) in tags"
        :key="index"
        :to="{ name: 'tag-tag', params: { tag: tag.name } }"
      >
        <Button size="sm" class="w-full rounded-sm bg-accent cursor-pointer">
          <div class="flex flex-1 justify-between">
            <p class="text-foreground">{{ tag.name }}</p>
            <div class="flex gap-2">
              <Separator orientation="vertical" />
              <p class="font-light text-foreground">{{ tag.count }}</p>
            </div>
          </div>
        </Button>
      </NuxtLink>
    </div>
  </div>
</template>
